### PR TITLE
Corrected regex for parsing gas total

### PR DESCRIPTION
**Pull request by Atrejoe**
Contains a general part (field identfier prefix) and specifically some for Kaifa meters (cubic meters indicator, unknown numeric prefix)

The regex seemded to missing a field indicator for 0-1:24.2.1
Furthermore my meter (and of @Koen01) seemded to have an extra prefixed field os some digits followed by 'S' and a cubinc meters indicator, like: `0-1:24.2.1(160904220000S)(05290.211*m3)`

Fixed by adding optional matching.

### CODE REVIEW

**Comment by nrocco** [comment]
Excellent work. Thanks for your contributions. 

I will merge this pull request now and create a new package + upload to pypi next week.

**Comment by Atrejoe** [comment]
Hi @nrocco do you maybe see the chance to update the pypi package?

**Comment by nrocco** [comment]
@Atrejoe I have just created a new version of `smeterd` `2.5.0` which can be found on pypi here:
https://pypi.python.org/pypi/smeterd/2.5.0

**Comment by Atrejoe** [comment]
Wow, that is a lightning response, thanks!

**Pull request merged**
