### PR TITLE
Added option to tweak output, updated description

### PR DESCRIPTION
**Pull request by tvwerkhoven**
1. Added --show-output to choose what output is displayed
2. Updated description (e.g. Electricity instead of kWh), updated
   unit to Wh (it's not kWh)

### CODE REVIEW

**Comment by nrocco** [comment]
Thanks for this contribution @tvwerkhoven, in the next 1 or 2 days I will play with the changes in your Pull Request and provide feedback and/or merge it.

**Comment by mpvader** [comment]
My 2 cents: replace electricity by energy in the wording

**Comment by Jorijn** [comment]
@nrocco update?

**Comment by nrocco** [comment]
@tvwerkhoven sorry for the delay. Finally found the time to try it out and looks good.

I just merged your Pull Request to master and marked it for the 2.8.0 milestone.

Which I will create after this.

Thanks for contributing.

**Comment by nrocco** [comment]
Version 2.8.0 available now on pypi.org: https://pypi.org/project/smeterd/

**Pull request merged**
