### PR TITLE
Add more cli options to configure the serial connection

### PR DESCRIPTION
**Pull request by nrocco**
@Atrejoe,

I have created the following pull request to add more configuration options. I was inspired by your commit in your fork.

Nothing sexy, though :)

### CODE REVIEW

**Comment by nrocco** [comment]
If you could help me test these flags that would be appreciated. I will work on updating the documentation in the next couple of days.

**Comment by Atrejoe** [comment]
I've tested the flags and they appear to be effective, sometimes really screwing up reading the meter. Is it true that  for enabling the software flow control I only have to enable `--xonxoff` ?

It seems my setup is quite robust; a lot of combinations work, and only a few don't. Settings that can actually break reading the serial port are the bytesize and parity.
Actually some of the values I mentioned at: https://github.com/nrocco/smeterd/issues/7#issuecomment-244457288 seems to break reading the meter.

Would it be an idea to log the used configuration in verbose mode? Like here: https://github.com/Atrejoe/smeterd/commit/eebd83a9dfd9b95b65d028945213b4c4b57a68f6

**Comment by nrocco** [comment]
New version `2.7.0` has been uploaded to pypi here:

https://pypi.python.org/pypi/smeterd/2.7.0

**Comment by nrocco** [comment]
@Atrejoe 

Thanks for your testing. It made me comfortable enough to start writing tests for it.

I have also taken the opportunity to prefix all serial console related options with `serial`.

So `--baudrate` is now called `--serial-baudrate`.

I maintained backwards compatibility by not removed `--baudrate` until version `3.x`.

I have uploaded the new version to pypi already and I can confirm that things work as it should for my smart meter.

And you are right, software flow control is off by default. If you want to turn it on you supply that option.

**Pull request merged**
